### ISSUE TITLE
Criar Docker para instalar Postgres e configurar Django para acessar esse banco

### ISSUE THREAD

**Issue by renzon** [devpro-br/django-template#8]

**Comment by huogerac** [comment]
- docker-compose com:
```yaml
  postgres:
    image: "postgres:15-alpine"
    ports:
      - 15432:5432
    expose:
      - "15432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure
```
- um .env com as variavies ou poderia ser o atributo environment: no compose acima
```yaml
POSTGRES_DB=db_core
POSTGRES_USER=core
POSTGRES_PASSWORD=core
DATABASE_URL=postgres://core:core@localhost:15432/db_core
```
- instalar o dj-database-url
- no settings adicionar:
```python
import dj_database_url
...
DATABASE_URL = config("DATABASE_URL")
ou
DATABASE_URL = os.getenv('DATABASE_URL')

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )
}
```
- vai precisar ter um python-decouple ou python dotenv para conseguir ler a variavel de ambiente
